### PR TITLE
Web3modal related features & fixes

### LINKED ISSUE #934: [feature] Expose all web3modal options in ethereum-provider
### What problem does this new feature solve?

We should expose all web3modal options in `@walletconnect/ethereum-provider` package.

### LINKED ISSUE #948: [feature] Add topic id and request id to request deeplinks
### Summary

When request is made for already established session, we are using raw deeplinks / universal links on mobile to link back into the mobile app, i.e `metamask://` or `https://metmask.io`

We should attach `wc` subpath with some additional context to make these more useful. Final links should look something like this

`metamask://wc?sessionTopic=...&requestId=...`
`https://metmask.io/wc?sessionTopic=...&requestId=...`

Once implemented, documentation needs to include this information.

### PR DESCRIPTION
**Pull request by xzilja**
# Description

- Makes `showQrModal` required
- Adds more options and fixes `qrModalOptions`
- Updated web3modal dep
- Decorates deeplinks with `sessionTopic` and `requestId`

docs pr https://github.com/WalletConnect/walletconnect-docs/pull/568

closes https://github.com/WalletConnect/web3modal/issues/948
closes https://github.com/WalletConnect/web3modal/issues/934

## How Has This Been Tested?

Internal tests

## Due Diligence

- [x] Breaking change
- [x] Requires a documentation update
  - [ ] Related docs issue/PR (if docs are not included in this PR):
- [ ] Requires a e2e/integration test update

### CODE REVIEW

File: providers/universal-provider/src/utils/deepLinks.ts [hunk 1]
```diff
@@ -9,18 +9,23 @@ export const handleDeepLinks = (client: InstanceType<typeof SignClient>, params:
     // only handle the request if it matches the request and topic
     if (payload.request !== params.request || payload.topic !== params.topic) return;
     client.events.removeListener("session_request_sent", handleSessionRequestSent);
-    deeplinkRedirect();
+    deeplinkRedirect(params.topic, params.id);
```
Comment (ganchoradkov) [inline providers/universal-provider/src/utils/deepLinks.ts]:
```suggestion
    deeplinkRedirect(params);
```
isnt it cleaner to pass the whole `params` as a single argument? If we need to use something else from the object it would be available without needing to update the fx arguments

File: providers/universal-provider/src/utils/deepLinks.ts [hunk 2]
```diff
@@ -9,18 +9,23 @@ export const handleDeepLinks = (client: InstanceType<typeof SignClient>, params:
...
   };
   client.on("session_request_sent", handleSessionRequestSent);
 };
 
-export function deeplinkRedirect() {
+export function deeplinkRedirect(topic: string, id?: number) {
```
Comment (ganchoradkov) [inline providers/universal-provider/src/utils/deepLinks.ts]:
```suggestion
export function deeplinkRedirect(request: RequestParams) {
const { topic, id } = request;
```

File: providers/universal-provider/src/types/misc.ts [hunk 3]
```diff
@@ -65,6 +65,7 @@ export interface RequestParams {
   topic: string;
   request: RequestArguments;
   chainId: string;
+  id?: number;
```
Comment (ganchoradkov) [inline providers/universal-provider/src/types/misc.ts:68]:
```suggestion
  id: number;
```
`Id` would be always present now so no need to be optional

File: providers/ethereum-provider/README.md [hunk 4]
```diff
@@ -16,19 +16,19 @@ import { EthereumProvider } from "@walletconnect/ethereum-provider";
...
-  qrModalOptions, // OPTIONAL - `undefined` by default, see https://docs.walletconnect.com/2.0/web3modal/theming
+  qrModalOptions, // OPTIONAL - `undefined` by default, see https://docs.walletconnect.com/2.0/web3modal/options
 });
 ```
 
 ## Display Web3Modal with QR code / Handle connection URI
 
 ```typescript
-// Web3Modal is enabled by default and will display a QR code modal
+// Web3Modal is dissabled by default, enable it during init() to display a QR code modal
```
Comment (ganchoradkov) [inline providers/ethereum-provider/README.md]:
```suggestion
// Web3Modal is disabled by default, enable it during init() to display a QR code modal
```

**Review by ganchoradkov — APPROVED** [review]
🥇 🥇
