### PR TITLE
fix: responding to request on disconnected session

### LINKED ISSUE #4063: Invalid session requests remain in the queue and new requests cannot be processed
**Describe the bug**
If the user disconnects while there are still pending requests and my wallet responds to them, an exception is thrown [in this line](https://github.com/WalletConnect/walletconnect-monorepo/blob/51c3a97db5895835e9fc997bee14a1de87202116/packages/sign-client/src/controllers/engine.ts#L384) which results in the [cleanup function](https://github.com/WalletConnect/walletconnect-monorepo/blob/51c3a97db5895835e9fc997bee14a1de87202116/packages/sign-client/src/controllers/engine.ts#L392) not being called. This means that those requests are not marked as completed and new requests cannot be processed. Only after 5 minutes will the queue get cleaned and new requests can be processed again.

**SDK Version (if relevant)**
 - Client: JS
 - Version 2.10.6

**Expected behavior**
The queue needs to be cleaned from invalid requests when such are detected, instead of waiting 5 minutes.

### PR DESCRIPTION
**Pull request by ganchoradkov**
## Description
Fixed a bug where trying to respond  to a session request on already disconnected session was causing the request queue to hang for the remaining expiry of that request

resolves https://github.com/WalletConnect/walletconnect-monorepo/issues/4063

## Type of change

- [ ] Chore (non-breaking change that addresses non-functional tasks, maintenance, or code quality improvements)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Draft PR (breaking/non-breaking change which needs more work for having a proper functionality _[Mark this PR as ready to review only when completely ready]_)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How has this been tested?
tests
dogfooding in example apps

## Checklist

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: packages/sign-client/src/controllers/engine.ts [hunk 1]
```diff
@@ -1039,7 +1044,7 @@ export class Engine extends IEngine {
   };
 
   private cleanupAfterResponse = (params: EngineTypes.RespondParams) => {
-    this.deletePendingSessionRequest(params.response.id, { message: "fulfilled", code: 0 });
+    this.deletePendingSessionRequest(params.response?.id, { message: "fulfilled", code: 0 });
```
Comment (bkrem) [inline packages/sign-client/src/controllers/engine.ts]: Why the change to optional chaining here? Can `deletePendingSessionRequest` handle being passed `undefined` if the optional chain operator defaults? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

File: packages/sign-client/src/controllers/engine.ts [hunk 2]
```diff
@@ -1388,7 +1393,11 @@ export class Engine extends IEngine {
       throw new Error(message);
     }
     const { topic, response } = params;
-    await this.isValidSessionTopic(topic);
+    // if the session is already disconnected, we can't respond to the request so we need to delete it
+    await this.isValidSessionTopic(topic).catch((error) => {
```
Comment (bkrem) [inline packages/sign-client/src/controllers/engine.ts]: Style nit: would prefer if we stick with imperative `try/catch + await` like in other places in the engine rather than mixing in Promise `then/catch`.

I get this is more convenient syntax wise but feels a bit out of place.

File: packages/sign-client/test/sdk/client.spec.ts [hunk 3]
```diff
@@ -346,6 +346,88 @@ describe("Sign Client Integration", () => {
...
+                    });
+                    _resolve();
+                  });
+                }
+                await clients.B.respond({
+                  topic,
+                  response: formatJsonRpcResult(id, "ok"),
+                }).catch((err) => {
+                  // eslint-disable-next-line no-console
+                  console.log("respond error", err);
```
Comment (bkrem) [inline packages/sign-client/test/sdk/client.spec.ts:409]: Still needed/wanted?

**Review by bkrem — APPROVED** [review]
💯 💯

File: packages/sign-client/src/controllers/engine.ts (hunk 1 above)
Comment (ganchoradkov) [reply packages/sign-client/src/controllers/engine.ts]: we have validation tests where params are forced empty and was resulting in an exception `.id of undefined`. Will think to handle it differently

File: packages/sign-client/test/sdk/client.spec.ts (hunk 3 above)
Comment (ganchoradkov) [reply packages/sign-client/test/sdk/client.spec.ts:409]: the log not, no but the catch is required to handle the rejection
