### PR TITLE
fix: namespace validation

### LINKED ISSUE #2002: engine#isValidApprove is validating to much.
**Describe the bug**
The engine's isValidApprove validates that that the entire optionalNamespace is in the approval, which it doesn't have to.

**To Reproduce**
```typescript
await dapp.connect({
  requiredNamespaces: {
    "eip155": {
      chains: ["eip155:16"],
      events: [],
      methods: ["eth_accounts", "personal_sign"],
    },
  },
  optionalNamespaces: {
    "eip155": {
      chains: ["eip155:14", "eip155:19", "eip155:114"],
      methods: ["wallet_switchEthereumChain"],
      events: [],
    },
    "eip155:5": {
      methods: ["eth_accounts"],
      events: [],
    },
  }
});
```

```typescript 
await wallet.approve({
  id: payload.id,
  namespaces: {
    eip155: {
      accounts: [
        'eip155:16:0x57f48fAFeC1d76B27e3f29b8d277b6218CDE6092',
        'eip155:114:0x57f48fAFeC1d76B27e3f29b8d277b6218CDE6092'
      ],
      events: [],
      methods: [ 'eth_accounts', 'personal_sign', 'wallet_switchEthereumChain' ]
    },
    'eip155:5': {
      accounts: [ 'eip155:5:0x57f48fAFeC1d76B27e3f29b8d277b6218CDE6092' ],
      events: [],
      methods: [ 'eth_accounts' ]
    }
  },
});
```

Engine throws `Non conforming namespaces. approve() namespaces accounts don't satisfy namespace chains for eip155`

https://github.com/WalletConnect/walletconnect-monorepo/blob/c643010944ff932cf33a9aff97647aff580bdeaa/packages/utils/src/validators.ts#L388-L390
Adding logging in path linked above 
```typescript
      const namespaceChains = getAccountsChains(namespaces[key].accounts);
      console.log(namespaceChains);
      console.log(getChainsFromNamespace(key, requiredNamespaces[key]))

      if (!hasOverlap(getChainsFromNamespace(key, requiredNamespaces[key]), namespaceChains)) {
```
Gives these results, first 2 is for requiredNamespaces, last 2 is for optionalNamespaces
```shell
    # requiredNamespaces
    [ 'eip155:16', 'eip155:114' ] # namespaceChains
    [ 'eip155:16' ] # getChainsFromNamespace()

    # optionalNamespaces
    [ 'eip155:16', 'eip155:114' ] # namespaceChains
    [ 'eip155:14', 'eip155:19', 'eip155:114' ] # getChainsFromNamespace()
```
**Expected behavior**
A successful connection as the required namespace is fulfilled and the optionalNamespace is partly fulfilled. 

> All required namespaces and all, none, or some of the optional namespaces (at the discretion of the provider) MUST be included if successful.

### PR DESCRIPTION
**Pull request by ganchoradkov**
# Description
PR to resolve an issue where required and approved namespaces had to match in structure in order to be accepted. 
Now we're correctly validating mix-structured namespaces.
Example:
Required namespaces
```
{
      "eip155:1": {
        events: [],
        methods: ["eth_accounts", "personal_sign"],
      },
      "eip155:2": {
        events: [],
        methods: ["eth_accounts"],
      },
      "solana:1": {
        events: [],
        methods: [],
      },
    };
```
is now correctly validated against reponse of
```
{
      eip155: {
        accounts: [
          "eip155:1:0x57f48fAFeC1d76B27e3f29b8d277b6218CDE6092",
          "eip155:2:0x57f48fAFeC1d76B27e3f29b8d277b6218CDE6092",
        ],
        events: [],
        methods: ["eth_accounts", "personal_sign"],
      },
      solana: {
        accounts: ["solana:1:0x57f48fAFeC1d76B27e3f29b8d277b6218CDE6092"],
        events: [],
        methods: [],
      },
    }
```

Resolves # ([browse](https://github.com/WalletConnect/walletconnect-monorepo/issues) or [create](https://github.com/WalletConnect/walletconnect-monorepo/issues/new/choose))

## How Has This Been Tested?
added bunch of validation tests

## Due Diligence

- [ ] Breaking change
- [ ] Requires a documentation update
  - [ ] Related docs issue/PR (if docs are not included in this PR):
- [ ] Requires a e2e/integration test update

### CODE REVIEW

File: packages/sign-client/src/controllers/engine.ts [hunk 1]
```diff
@@ -955,28 +954,6 @@ export class Engine extends IEngine {
...
-      const namespacesToValidate = Object.keys(proposal.optionalNamespaces).filter(
-        (namespace) => namespaces[namespace],
-      );
-      const usedOptionalNamespaces = {};
-      for (const key in proposal.optionalNamespaces) {
-        if (namespacesToValidate.includes(key)) {
-          usedOptionalNamespaces[key] = proposal.optionalNamespaces[key];
-        }
-      }
-      const conformingNamespacesError = isConformingNamespaces(
```
Comment (bkrem) [inline packages/sign-client/src/controllers/engine.ts:971]: A lot going on here so not immediately clear to me why we can kick this whole block of validation out, I'm guessing it's too rigid based on the now more dynamic parsing approach?

File: packages/utils/src/validators.ts [hunk 2]
```diff
@@ -370,45 +370,108 @@ export function isConformingNamespaces(
...
+    }
+  });
+
   return error;
 }
 
+function parseNamespaces(namespaces: ProposalTypes.RequiredNamespaces) {
+  const parsed = {};
+  Object.keys(namespaces).forEach((key) => {
+    const isInlineDefinition = key.includes(":");
```
Comment (bkrem) [inline packages/utils/src/validators.ts]: Tweaking slightly to make it clearer what's inline here

```suggestion
    const isInlineChainDefinition = key.includes(":");
```

File: packages/utils/src/validators.ts [hunk 3]
```diff
@@ -370,45 +370,108 @@ export function isConformingNamespaces(
...
+
+    if (isInlineDefinition) {
```
Comment (bkrem) [inline packages/utils/src/validators.ts]:
```suggestion
    // e.g. `eip155:1`
    if (isInlineChainDefinition) {
```

File: packages/utils/src/validators.ts [hunk 4]
```diff
@@ -370,45 +370,108 @@ export function isConformingNamespaces(
...
+        namespace.includes(":") ? namespace.split(":")[0] : namespace,
+      ),
+    ),
+  ];
+}
+
+function parseApprovedNamespaces(namespaces: SessionTypes.Namespaces) {
+  const parsed = {};
+  Object.keys(namespaces).forEach((key) => {
+    const isInlineDefinition = key.includes(":");
```
Comment (bkrem) [inline packages/utils/src/validators.ts]:
```suggestion
    const isInlineChainDefinition = key.includes(":");
```

File: packages/utils/src/validators.ts [hunk 5]
```diff
@@ -370,45 +370,108 @@ export function isConformingNamespaces(
...
+    if (isInlineDefinition) {
```
Comment (bkrem) [inline packages/utils/src/validators.ts]:
```suggestion
    // e.g. `eip155:1`
    if (isInlineChainDefinition) {
```

File: packages/utils/test/validators.spec.ts [hunk 6]
```diff
@@ -106,4 +106,167 @@ describe("Validators", () => {
       }),
     ).to.be.false;
   });
+  it("should validate namespaces v1", () => {
```
Comment (bkrem) [inline packages/utils/test/validators.spec.ts]: Would avoid using `v1/2/3` terminology here since it could imply we have different versioning for namespaces

```suggestion
  it("should validate namespaces (configuration 1)", () => {
```

File: packages/utils/test/validators.spec.ts [hunk 7]
```diff
@@ -106,4 +106,167 @@ describe("Validators", () => {
...
+          "solana:3:0x57f48fAFeC1d76B27e3f29b8d277b6218CDE6092",
+        ],
+        events: [],
+        methods: ["eth_accounts", "personal_sign"],
+      },
+    };
+    const err = isConformingNamespaces(required, approved, "validators");
+    expect(err).to.be.null;
+  });
+  it("should validate namespaces v2", () => {
```
Comment (bkrem) [inline packages/utils/test/validators.spec.ts]:
```suggestion
  it("should validate namespaces (configuration 2)", () => {
```

File: packages/utils/test/validators.spec.ts [hunk 8]
```diff
@@ -106,4 +106,167 @@ describe("Validators", () => {
...
+      solana: {
+        accounts: ["solana:1:0x57f48fAFeC1d76B27e3f29b8d277b6218CDE6092"],
+        events: [],
+        methods: ["eth_accounts", "personal_sign"],
+      },
+    };
+    const err = isConformingNamespaces(required, approved, "validators");
+    expect(err).to.be.null;
+  });
+  it("should validate namespaces v3", () => {
```
Comment (bkrem) [inline packages/utils/test/validators.spec.ts]:
```suggestion
  it("should validate namespaces (configuration 3)", () => {
```

File: packages/utils/test/validators.spec.ts [hunk 9]
```diff
@@ -106,4 +106,167 @@ describe("Validators", () => {
...
+        ],
+        events: ["chainChanged"],
+        methods: ["eth_accounts", "personal_sign"],
+      },
+    };
+    const err = isConformingNamespaces(required, approveOptional, "validators");
+    expect(err).to.be.null;
+  });
+
+  it("should trow on invalid accounts", () => {
```
Comment (bkrem) [inline packages/utils/test/validators.spec.ts]:
```suggestion
  it("should throw on invalid accounts", () => {
```

File: packages/utils/test/validators.spec.ts [hunk 10]
```diff
@@ -106,4 +106,167 @@ describe("Validators", () => {
...
+    const approveOptional = {
+      eip155: {
+        accounts: ["eip155:2:0x57f48fAFeC1d76B27e3f29b8d277b6218CDE6092"],
+        events: ["chainChanged"],
+        methods: ["eth_accounts", "personal_sign"],
+      },
+    };
+    expect(isConformingNamespaces(required, approveOptional, "validators")).to.throw;
+  });
+  it("should trow on invalid namespace", () => {
```
Comment (bkrem) [inline packages/utils/test/validators.spec.ts]:
```suggestion
  it("should throw on invalid namespace", () => {
```

File: packages/utils/test/validators.spec.ts [hunk 11]
```diff
@@ -106,4 +106,167 @@ describe("Validators", () => {
...
+    const approveOptional = {
+      solana: {
+        accounts: ["solana:1:0x57f48fAFeC1d76B27e3f29b8d277b6218CDE6092"],
+        events: ["chainChanged"],
+        methods: ["eth_accounts", "personal_sign"],
+      },
+    };
+    expect(isConformingNamespaces(required, approveOptional, "validators")).to.throw;
+  });
+  it("should trow on invalid methods", () => {
```
Comment (bkrem) [inline packages/utils/test/validators.spec.ts]:
```suggestion
  it("should throw on invalid methods", () => {
```

**Review by bkrem — APPROVED** [review]
Great stuff, thanks for getting this worked out 💯 💯 A lot better normalisation between requested and approved namespace configurations now. 

All comments minor, mainly contextual and terminology/typo fixes.

File: packages/sign-client/src/controllers/engine.ts (hunk 1 above)
Comment (ganchoradkov) [reply packages/sign-client/src/controllers/engine.ts:971]: I removed it because we don't really need to check the `optional` namespaces. As long as the structure is correct (types responsibility) we're OK

Comment (bkrem) [reply packages/sign-client/src/controllers/engine.ts:971]: 👍🙇‍♂️

**Comment by antondalgren** [comment]
Adding 2 more testcases that I don't see covered, where the first one passes, and the second doesn't. 

The fact that the second testcase doesn't pass, means there is a bug in the code that should be fixed.

```typescript
  it("should validate namespaces (configuration 4)", () => {
    const required = {
      eip155: {
        chains: ["eip155:1", "eip155:2"],
        events: [],
        methods: ["eth_accounts"],
      },
    };

    const approveOptional = {
      "eip155:1": {
        accounts: [
          "eip155:1:0x57f48fAFeC1d76B27e3f29b8d277b6218CDE6092",
        ],
        events: ["chainChanged"],
        methods: ["eth_accounts"],
      },
      "eip155:2": {
        accounts: [
          "eip155:2:0x57f48fAFeC1d76B27e3f29b8d277b6218CDE6092",
        ],
        events: ["chainChanged"],
        methods: ["eth_accounts"],
      },
    };
    const err = isConformingNamespaces(required, approveOptional, "validators");
    expect(err).to.be.null;
  });
```

```typescript
  it("should throw on CAIP2 namespace not including that CAIP2 in accouns", () => {
    const required = {
      eip155: {
        chains: ["eip155:1", "eip155:2"],
        events: [],
        methods: ["eth_accounts"],
      },
    };

    const approveOptional = {
      "eip155:1": {
        accounts: [
          "eip155:1:0x57f48fAFeC1d76B27e3f29b8d277b6218CDE6092",
        ],
        events: ["chainChanged"],
        methods: ["eth_accounts"],
      },
      "eip155:2": {
        accounts: [
          "eip155:1:0x57f48fAFeC1d76B27e3f29b8d277b6218CDE6092",
        ],
        events: ["chainChanged"],
        methods: ["eth_accounts"],
      },
    };
    expect(isConformingNamespaces(required, approveOptional, "validators")).to.throw;
  });
```

Thank you for the good job on this lib. @ganchoradkov
