### PR TITLE
fix: ethereum provider persisted session with inline chain declaration

### LINKED ISSUE #2277: Error in loading persisted session [Cannot read properties of undefined (reading 'accounts')]
**Describe the bug**
Some persisted sessions cannot be correctly reloaded when the dApp is restarted. This happens with the `ethereum-provider` and Bifrost wallet. It doesn't happen with D'CENT or SafePal that likely have a more basic namespace handling and manipulation.

**SDK Version (if relevant)**
 - Client: ethereum-provider
 - Version 2.7.2

**To Reproduce**
1. Go to https://walletconnectv2.frontend-3y1.pages.dev/
2. Click on Connect Wallet and select WalletConnect
3. Establish the session with Bifrost (beta version not available in app store)
4. Reload the page

**Expected behavior**
The connection to the wallet is maintained

**Screenshots**
image
```
TpeError: Cannot read properties of undefined (reading 'accounts')
    at Xc.loadPersistedSession (_layout.svelte-a822f215.js:100:40464)
```

**Additional context**
I can provide the content of the Local Storage if you need, just tell me which keys you need.

### PR DESCRIPTION
**Pull request by ganchoradkov**
## Description
Fixed an issue where `loadPersistedSession` fx was not catering to inline chain declared namespaces e.g. `eip155:1`
additionally
- Added `relayUrl` to init params
- Added `storageOptions` to init params
- Renamed `setHttpProvider` fx to `switchEthereumChain` as its more appropriate name for what it does

## Type of change

- [x] Chore (non-breaking change that addresses non-functional tasks, maintenance, or code quality improvements)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Draft PR (breaking/non-breaking change which needs more work for having a proper functionality _[Mark this PR as ready to review only when completely ready]_)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How has this been tested?
tests

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: providers/ethereum-provider/src/EthereumProvider.ts [hunk 1]
```diff
@@ -538,10 +543,14 @@ export class EthereumProvider implements IEthereumProvider {
   protected async loadPersistedSession() {
     if (!this.session) return;
     const chainId = await this.signer.client.core.storage.getItem(`${this.STORAGE_KEY}/chainId`);
-    this.setChainIds(
-      chainId ? [this.formatChainId(chainId)] : this.session.namespaces[this.namespace].accounts,
-    );
-    this.setAccounts(this.session.namespaces[this.namespace].accounts);
+
+    // cater to both inline & nested namespace formats
+    const namespace = this.session.namespaces[this.namespace]
```
Comment (xzilja) [inline providers/ethereum-provider/src/EthereumProvider.ts]: Should this be reversed? i.e try `this.session.namespaces[`${this.namespace}:${chainId}`]` first and then do general namespace?

**Comment by bkrem** [comment]
Resolves #2645

**Review by xzilja — APPROVED** [review]

**Review by bkrem — APPROVED** [review]
💪
